### ISSUE TITLE
Doesn't work with Sketch 44

### ISSUE THREAD

**Issue by stas-mikhailov** [bomberstudios/Cleanup-Useless-Groups#4]
Just doesn't work with Sketch 44 :( I hope you'll fix it

**Comment by RaphyRaph** [comment]
https://www.dropbox.com/s/31x918mlx3z52jy/cleanup%20groups.mov?dl=0
I confirm.

**Comment by bomberstudios** [comment]
Turns out this was an error on my side, and the plugin has never worked with groups inside Artboards, so this has nothing to do with Sketch 44.

Will push a fix in a second.
